name: copy files # Thaddus Haase example of testing and deploying
on:
  push:
    branches: [ "test" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: build site
        run: |
          cd ./site
          bundle install
          bundle exec jekyll build
      - name: check html files
        run: |
            cd ./site
            bundle install
            rake test
      - name: Copy Files
        run: |
          cp -r ./site/_site/* ./docs/.
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./docs
          git commit -m "Updating docs folder"
          git push
      - name: build site for netlify
        run: |
          cd ./site
          bundle install
          bundle exec jekyll build -b ""
      - name: Copy Files netlify
        run: |
          cp -r ./site/_site/* ./netlify/.
      - name: netlify files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./netlify
          git commit -m "Updating netlify folder"
          git push
